"""empty message

Revision ID: 50be1d7bf21a
Revises: 2cc50658b65c
Create Date: 2024-11-08 18:44:12.483914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50be1d7bf21a'
down_revision = '2cc50658b65c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_premium', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_premium')

    # ### end Alembic commands ###
