"""empty message

Revision ID: d584f98b1d57
Revises: f83bfe8fa4e3
Create Date: 2024-10-23 18:18:32.522736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd584f98b1d57'
down_revision = 'f83bfe8fa4e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ideas')
    with op.batch_alter_table('favorite_ideas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('area', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('budget', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_ideas', schema=None) as batch_op:
        batch_op.drop_column('budget')
        batch_op.drop_column('area')
        batch_op.drop_column('country')

    op.create_table('ideas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('area', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('budget', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ideas_pkey')
    )
    # ### end Alembic commands ###
